[package]
name = 'dirtyparallel'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'dirtyparallel'

[dependencies]
extendr-api = '*'
rayon = '*'

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
