# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dirtyparallel_wrappers", use_symbols = TRUE, package_name = "dirtyparallel")

#' @usage NULL
#' @useDynLib dirtyparallel, .registration = TRUE
NULL

#' dirtylapply replicates R's lapply: it takes an R list and an R function,
#' applies the function to each element, and returns a new list of results.
dirtylapply <- function(list, func) .Call(wrap__dirtylapply, list, func)


# nolint end
