# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dirtyparallel_wrappers", use_symbols = TRUE, package_name = "dirtyparallel")

#' @usage NULL
#' @useDynLib dirtyparallel, .registration = TRUE
NULL

#' dirtylapply replicates R's lapply: it takes an R list and an R function,
#' applies the function to each element, and returns a new list of results.
rustylapply <- function(list, func, varargs) .Call(wrap__rustylapply, list, func, varargs)

call_rust_with_varargs <- function(args) .Call(wrap__call_rust_with_varargs, args)


# nolint end
